{{- if .Values.kciss.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kciss.kciss.serviceAccountName" . }}
  labels:
    {{- include "kciss.kciss.labels" . | nindent 4 }}
{{- end -}}
