{{- if .Values.ingress.enabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "kciss.kciss.fullname" . }}-tls-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "ingress.self-signed.cert" . ) | indent 2 }}
{{- end -}}
