apiVersion: v1
kind: Service
metadata:
  name: {{ template "kciss.kciss.fullname" . }}
  {{- with .Values.kciss.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kciss.kciss.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kciss.kciss.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.kciss.port }}
      protocol: TCP
      targetPort: {{ .Values.kciss.targetPort }}
