---
{{- if .Values.trivy.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kciss.trivy.serviceAccountName" . }}
  labels:
    {{- include "kciss.trivy.labels" . | nindent 4 }}
{{- end -}}
