apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kciss.trivy.fullname" . }}
  labels:
    {{- include "kciss.trivy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.trivy.replicaCount }}
  selector:
    matchLabels:
      {{- include "kciss.trivy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kciss.trivy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "kciss.trivy.serviceAccountName" . }}
      containers:
        - name: trivy-server
          image: "{{ .Values.trivy.image.repository }}:{{ .Values.trivy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.trivy.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.trivy.port }}
          command: ["/usr/local/bin/trivy","server","--listen","0.0.0.0:{{ .Values.trivy.port }}"]
          securityContext:
            {{- toYaml .Values.trivy.containerSecurityContext | nindent 12 }}
      {{- with .Values.trivy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.trivy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.trivy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
