apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "kciss.trivy.labels" . | nindent 4 }}
  name: {{ template "kciss.trivy.fullname" . }}
spec:
  type: ClusterIP
  selector:
      {{- include "kciss.trivy.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.trivy.port }}
      protocol: TCP
      targetPort: {{ .Values.trivy.port }}