apiVersion: k3d.io/v1alpha2
kind: Simple
name: mycluster
servers: 1
agents: 1
kubeAPI:
  hostPort: "6443"
image: rancher/k3s:latest
ports:
  - port: 1443:443
    nodeFilters:
      - loadbalancer
  - port: 1080:80
    nodeFilters:
      - loadbalancer
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableImageVolume: false
  k3s:
    extraServerArgs:
      - --tls-san=127.0.0.1
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
