apiVersion: v1
kind: Namespace
metadata:
  name: example-old-nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pods-with-vulnerabilities
  namespace: example-old-nginx
spec:
  containers:
  - name: old-nginx
    image: nginx:1.19.0