# Default values for kciss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kciss:
  replicaCount: 1
  port: 9300
  targetPort: 9300
  interval: 3600
  endpoint: "/kciss-metrics"
  image:
    repository: sokube/kciss
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
  containerSecurityContext:
    runAsUser: 2000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/kciss-metrics"
  extraContainers: []
  extraVolumes: []

trivy:
  replicaCount: 1
  port: 8080
  image:
    repository: sokube/kciss
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
  containerSecurityContext:
    runAsUser: 2000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podAnnotations: {}
imagePullSecrets: []

ingress:
  enabled: false
  address: "mycluster.example.com"
