# Default values for kciss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kciss:
  replicaCount: 1
  port: 9300
  interval: 3600
  image:
    repository: sokube/trivy-rootless
    tag: 0.1.2
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: kciss
  containerSecurityContext:
    runAsUser: 2000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAnnotations:
    - prometheus.io/scrape: "true"

trivy:
  replicaCount: 1
  port: 8080
  image:
    repository: sokube/trivy-rootless
    pullPolicy: IfNotPresent
    tag: 0.1.2
  serviceAccount:
    create: true
    name: trivy
  containerSecurityContext:
    runAsUser: 2000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podAnnotations: {}
imagePullSecrets: []

prometheus:
  serviceMonitor:
    metricRelabeling:
      []
      # - sourceLabels:
      #     - __address__
      #   targetLabel: project
      #   replacement: svc0041wbhst
      # - sourceLabels:
      #     - __address__
      #   targetLabel: line
      #   replacement: test
  alertRules:
    - alert: application-workloads-vulnerabilities-detected
      annotations:
        description: Namespace {{ $labels.namespace }} has {{ $value }} critical vulnerabilities reported
        summary: Critical vulnerabilities in cluster application workloads
      expr: namespace_vulnerabilities_total{severity="critical", namespace!~"logging|monitoring|pks-system|projectcontour|kube-system"} > 0
      for: 10m
      labels:
        severity: critical
    - alert: system-workloads-vulnerabilities-detected
      annotations:
        description: Namespace {{ $labels.namespace }} has {{ $value }} critical vulnerabilities reported
        summary: Critical vulnerabilities in cluster system workloads
      expr: namespace_vulnerabilities_total{severity="critical", namespace=~"logging|monitoring|pks-system|projectcontour|kube-system"} > 0
      for: 10m
      labels:
        severity: critical
