name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Get version from tag
      id: get_version_tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Get the version from file
      id: get_version_file
      run: echo ::set-output name=VERSION::$(grep -oP "TRIVY_VERSION=(\K.*)" docker/trivyrootless.Dockerfile)
      
    - name: Build the trivy rootless Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build --file docker/trivyrootless.Dockerfile --tag sokube/trivy-rootless:${{ steps.get_version_file.outputs.VERSION }} .

    - name: Build the kciss Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build --file docker/kciss.Dockerfile --tag sokube/kciss:${{ steps.get_version_tag.outputs.VERSION }} .
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push the images
      run: |
        docker push sokube/kciss:${{ steps.get_version_tag.outputs.VERSION }}
        docker push sokube/trivy-rootless:${{ steps.get_version_file.outputs.VERSION }}
