name: Docker Image CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get version from tag
        id: get_version_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}

      - name: Build the kciss Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --file docker/kciss.Dockerfile --tag sokube/kciss:${{ steps.get_version_tag.outputs.VERSION }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the kciss image
        run: |
          docker tag sokube/kciss:${{ steps.get_version_tag.outputs.VERSION }} sokube/kciss:latest
          docker push sokube/kciss:${{ steps.get_version_tag.outputs.VERSION }}
          docker push sokube/kciss:latest
